defmodule KdabetFrontendWeb.Components.King do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  @doc "The image of the twitter pfp"
  prop(imageurl, :string, required: true)

  @doc "The twitter handle"
  prop(twitter, :string, required: true)

  def render(assigns) do
    ~F"""
    <a
      class="kinglink block w-full h-full hover:"
      target="_blank"
      rel="noopener noreferrer"
      href={"https://twitter.com/" <> @twitter}
    >
      <img class="w-full h-full" src={"/images/pfps/" <> @imageurl}>
        <span class="tooltip flex flex-col invisible md:visible">
          <span>Handle: @{@twitter}</span>
          <hr class="mb-2" />
          <span>King Name: TBD</span><br>
          <span>Mint Status: Unminted</span>
        </span>
    </a>
    """
  end
end
