defmodule KdabetFrontendWeb.Components.King do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  @doc "The twitter url"
  prop(imageurl, :string, required: true)

  def render(assigns) do
    ~F"""
    <a class="block w-full h-full" href="/about">
      <img class="w-full h-full" src={"/images/pfps/"<>@imageurl}>
    </a>
    """
  end
end
