defmodule KdabetFrontendWeb.Components.King do
  @moduledoc """
  A sample component generated by `mix surface.init`.
  """
  use Surface.Component

  @doc "The image of the twitter pfp"
  prop(imageurl, :string, required: true)

  @doc "The twitter handle"
  prop(twitter, :string, required: true)

  def render(assigns) do
    ~F"""
    <a class="block w-full h-full hover:" target="_blank" rel="noopener noreferrer" href={"https://twitter.com/"<>@twitter}>
      <img class="w-full h-full" src={"/images/pfps/"<>@imageurl}>
    </a>
    """
  end
end
