defmodule Core.Repo.Migrations.Statcast do
  use Ecto.Migration

  def change do
    create table(:statcast) do
      add :plate_x, :float
      add :fielder_4, :integer
      add :sv_id, :string
      add :sz_top, :float
      add :az, :float
      add :vx0, :float
      add :batter, :integer
      add :sz_bot, :float
      add :ax, :float
      add :fielder_9, :integer
      add :woba_denom, :integer
      add :umpire, :integer
      add :woba_value, :float
      add :release_pos_z, :float
      add :pitcher, :integer
      add :fielder_6, :integer
      add :post_bat_score, :integer
      add :break_length_deprecated, :float
      add :fielder_8, :integer
      add :release_extension, :float
      add :type, :string
      add :vz0, :float
      add :babip_value, :integer
      add :delta_home_win_exp, :float
      add :delta_run_exp, :float
      add :pitch_name, :string
      add :ay, :float
      add :if_fielding_alignment, :string
      add :game_year, :integer
      add :away_score, :integer
      add :zone, :integer
      add :bat_score, :integer
      add :estimated_ba_using_speedangle, :float
      add :post_away_score, :integer
      add :iso_value, :integer
      add :fld_score, :integer
      add :home_team, :string
      add :spin_axis, :integer
      add :bb_type, :string
      add :on_1b, :integer
      add :on_2b, :integer
      add :on_3b, :integer
      add :player_name, :string
      add :home_score, :integer
      add :release_pos_x, :float
      add :of_fielding_alignment, :string
      add :launch_speed_angle, :integer
      add :tfs_deprecated, :string
      add :game_type, :string
      add :vy0, :float
      add :launch_angle, :integer
      add :release_pos_y, :float
      add :pitch_type, :string
      add :fielder_5, :integer
      add :fielder_7, :integer
      add :p_throws, :string
      add :balls, :integer
      add :events, :string
      add :effective_speed, :float
      add :at_bat_number, :integer
      add :launch_speed, :float
      add :pitch_number, :integer
      add :des, :text
      add :pfx_z, :float
      add :hit_distance_sc, :integer
      add :tfs_zulu_deprecated, :integer
      add :post_fld_score, :integer
      add :break_angle_deprecated, :float
      add :strikes, :integer
      add :estimated_woba_using_speedangle, :float
      add :hit_location, :integer
      add :release_speed, :float
      add :release_spin_rate, :integer
      add :game_date, :string
      add :away_team, :string
      add :inning, :integer
      add :outs_when_up, :integer
      add :description, :string
      add :inning_topbot, :string
      add :fielder_2, :integer
      add :spin_dir, :float
      add :post_home_score, :integer
      add :hc_y, :float
      add :fielder_3, :integer
      add :hc_x, :float
      add :stand, :string
      add :spin_rate_deprecated, :integer
      add :plate_z, :float
      add :pfx_x, :float
      add :game_pk, :integer
    end

    create index(:statcast, [:game_pk, :at_bat_number, :pitch_number])  
 
  end
end
